// src/lib/category-seo-data.ts

export const categorySEOData: Record<string, { title: string; description: string }> = {
  "movers": {
    title: "Trusted Movers & Packers in the UAE",
    description: "Looking for reliable movers and packers in Dubai, Abu Dhabi, or Sharjah? EasyFinder connects you with verified, professional relocation companies offering comprehensive packing, safe transportation, and efficient unpacking services. Whether you are moving a villa, apartment, or office across the UAE, our trusted partners ensure your belongings are handled with the utmost care, providing licensed, insured, and stress-free moving experiences tailored to your schedule."
  },
  "plumbers": {
    title: "Licensed Plumbers & Leak Detection in the UAE",
    description: "Find expert, licensed plumbers across Dubai, Abu Dhabi, and Sharjah for all your residential and commercial needs. From emergency leak detection and pipe repairs to bathroom fittings and water heater installations, our verified plumbing professionals offer prompt, reliable, and transparently priced services. Don't let a plumbing issue disrupt your day; connect with top-rated UAE plumbing experts who guarantee quality workmanship and lasting solutions."
  },
  "electricians": {
    title: "Certified Electricians & Electrical Services in the UAE",
    description: "Ensure your home or business is safe with certified electricians in Dubai, Abu Dhabi, and across the UAE. EasyFinder features verified professionals specializing in wiring, circuit breaker repairs, lighting installation, and emergency electrical troubleshooting. Our trusted electrical contractors adhere to strict UAE safety standards, providing prompt, reliable, and affordable solutions for all your residential and commercial electrical needs."
  },
  "photographers": {
    title: "Professional Photographers in the UAE",
    description: "Capture your most important moments with top-rated professional photographers in Dubai, Abu Dhabi, and Sharjah. Whether you need stunning wedding photography, corporate headshots, real estate shoots, or creative portrait sessions, EasyFinder connects you with verified, talented artists. Browse portfolios, compare styles, and book the perfect photographer to bring your vision to life with high-quality, memorable imagery."
  },
  "wedding-planners": {
    title: "Expert Wedding Planners in the UAE",
    description: "Plan your dream wedding with the UAE's most trusted wedding planners and coordinators. From intimate ceremonies to grand luxury events in Dubai, Abu Dhabi, and beyond, our verified professionals handle every detail. Enjoy stress-free planning with expert vendor management, venue selection, decor design, and seamless day-of coordination, ensuring your special day is absolutely perfect and uniquely tailored to your vision."
  },
  "carpenters": {
    title: "Skilled Carpenters & Woodwork Services in the UAE",
    description: "Discover highly skilled carpenters in Dubai, Abu Dhabi, and Sharjah for all your custom woodwork needs. Whether you require bespoke furniture creation, kitchen cabinet installations, door repairs, or intricate wooden detailing, our verified craftsmen deliver exceptional quality and precision. Trust EasyFinder to connect you with reliable, experienced carpentry professionals who bring durability and aesthetic excellence to your home or office."
  },
  "car-rentals": {
    title: "Reliable Car Rental Services in the UAE",
    description: "Find the best car rental deals across Dubai, Abu Dhabi, and the wider UAE with EasyFinder. We connect you with verified, reputable rental agencies offering a wide range of vehicles, from economical city cars to luxury SUVs and family vans. Enjoy transparent pricing, comprehensive insurance options, and flexible short-term or long-term rental agreements, ensuring a smooth and comfortable driving experience throughout the Emirates."
  },
  "garage-car-repair": {
    title: "Trusted Auto Repair & Garage Services in the UAE",
    description: "Keep your vehicle in peak condition with certified auto repair shops and garages in Dubai, Abu Dhabi, and Sharjah. EasyFinder features verified mechanics specializing in engine diagnostics, brake repairs, routine maintenance, and complex mechanical overalls. Drive with confidence knowing our trusted automotive professionals use high-quality parts and offer transparent, fair pricing for all car makes and models."
  },
  "car-wash": {
    title: "Professional Car Wash & Detailing in the UAE",
    description: "Keep your vehicle looking pristine with top-rated car wash and detailing services across the UAE. From convenient mobile car wash options in Dubai and Abu Dhabi to comprehensive interior deep-cleaning and exterior polishing, our verified providers deliver exceptional results. Trust EasyFinder to connect you with reliable, eco-friendly car care professionals who treat your vehicle with the utmost attention to detail."
  },
  "ac-repair-maintenance": {
    title: "Expert AC Repair & Maintenance in the UAE",
    description: "Beat the UAE heat with reliable, certified AC repair and maintenance services in Dubai, Abu Dhabi, and Sharjah. EasyFinder connects you with verified HVAC technicians specializing in emergency repairs, routine servicing, duct cleaning, and new unit installations. Ensure your home or office stays cool and energy-efficient with prompt, professional, and transparently priced air conditioning solutions from trusted local experts."
  },
  "cleaning-services": {
    title: "Professional Cleaning & Maid Services in the UAE",
    description: "Maintain a spotless home or office with trusted cleaning and maid services across Dubai, Abu Dhabi, and Sharjah. EasyFinder features verified, background-checked cleaning professionals offering everything from routine housekeeping and deep cleaning to post-construction cleanup and sofa shampooing. Enjoy peace of mind with reliable, thorough, and affordable cleaning solutions tailored to your specific schedule and requirements."
  },
  "painters": {
    title: "Professional Painters & Decorating Services in the UAE",
    description: "Transform your space with skilled, professional painters in Dubai, Abu Dhabi, and across the UAE. Whether you need interior wall painting, exterior facade refurbishment, or specialized decorative finishes, our verified contractors deliver flawless, long-lasting results. EasyFinder connects you with reputable painting services that use high-quality, weather-resistant materials and offer clean, efficient, and transparently priced workmanship."
  },
  "pest-control": {
    title: "Licensed Pest Control & Fumigation in the UAE",
    description: "Protect your home and business with municipal-approved pest control and fumigation services in Dubai, Abu Dhabi, and Sharjah. EasyFinder connects you with verified, eco-friendly pest management experts specializing in cockroach, bed bug, termite, and rodent elimination. Ensure a safe, hygienic environment with prompt, effective, and guaranteed treatments from licensed UAE pest control professionals."
  },
  "appliance-repair": {
    title: "Expert Home Appliance Repair in the UAE",
    description: "Don't let a broken appliance disrupt your routine. Find certified appliance repair technicians in Dubai, Abu Dhabi, and Sharjah for fast, reliable fixes. Our verified professionals specialize in repairing refrigerators, washing machines, ovens, dishwashers, and more. Enjoy transparent diagnostics, genuine spare parts, and guaranteed workmanship, extending the life of your essential home appliances with trusted local expertise."
  },
  "locksmith": {
    title: "24/7 Emergency Locksmith Services in the UAE",
    description: "Locked out? Find rapid, reliable, and 24/7 emergency locksmith services across Dubai, Abu Dhabi, and Sharjah. EasyFinder connects you with verified, licensed locksmith professionals specializing in residential and commercial lock installation, key duplication, safe opening, and emergency lockout assistance. Trust our responsive experts to restore your security quickly, professionally, and without causing damage to your property."
  },
  // ... (Adding the rest of the 60 categories concisely to ensure full coverage)
  "tv-mounting-installation": { title: "Professional TV Mounting in the UAE", description: "Secure your entertainment setup with expert TV mounting and home theater installation services in Dubai, Abu Dhabi, and Sharjah. Our verified technicians ensure safe, wall-mounted installations with hidden cable management, providing a clean, professional finish for your home or office." },
  "furniture-assembly": { title: "Reliable Furniture Assembly in the UAE", description: "Save time and avoid frustration with professional furniture assembly services across the UAE. Our verified handymen in Dubai, Abu Dhabi, and Sharjah expertly assemble flat-pack, modular, and custom furniture, ensuring sturdy, precise, and damage-free setup for your home or office." },
  "general-contractor": { title: "Trusted General Contractors in the UAE", description: "Manage your construction or renovation project with confidence using verified general contractors in Dubai, Abu Dhabi, and Sharjah. EasyFinder connects you with experienced professionals who handle full-scale project management, permitting, and coordination, delivering high-quality results on time and within budget." },
  "interior-designer": { title: "Creative Interior Designers in the UAE", description: "Transform your living or working space with talented, verified interior designers in Dubai, Abu Dhabi, and the wider UAE. From concept development and 3D rendering to material sourcing and final styling, our professionals create functional, aesthetically stunning environments tailored to your unique taste and budget." },
  "landscaping": { title: "Professional Landscaping & Garden Services in the UAE", description: "Create a stunning outdoor oasis with expert landscaping and garden maintenance services across the UAE. Our verified professionals in Dubai, Abu Dhabi, and Sharjah specialize in garden design, lawn care, irrigation systems, and hardscaping, bringing vibrant, sustainable beauty to your property." },
  "swimming-pool-maintenance": { title: "Expert Pool Maintenance & Cleaning in the UAE", description: "Keep your swimming pool pristine and safe with professional maintenance and cleaning services in Dubai, Abu Dhabi, and Sharjah. Our verified technicians offer regular cleaning, chemical balancing, pump repair, and equipment maintenance, ensuring your pool is always ready for a refreshing dip." },
  "security-systems-cctv": { title: "Reliable CCTV & Security Systems in the UAE", description: "Protect your property with advanced, verified security system and CCTV installation services across the UAE. Our certified technicians in Dubai, Abu Dhabi, and Sharjah provide comprehensive surveillance solutions, including camera setup, alarm integration, and remote monitoring, giving you complete peace of mind." },
  "internet-cable-installation": { title: "Professional Internet & Network Installation in the UAE", description: "Ensure seamless connectivity with expert internet, networking, and cable TV installation services in the UAE. Our verified technicians in Dubai, Abu Dhabi, and Sharjah handle structured cabling, router setup, and Wi-Fi optimization for homes and businesses, guaranteeing fast, reliable, and stable connections." },
  "water-tank-cleaning": { title: "Professional Water Tank Cleaning in the UAE", description: "Ensure safe, clean drinking water with certified water tank cleaning and disinfection services across Dubai, Abu Dhabi, and Sharjah. Our verified professionals use approved, eco-friendly methods to remove sediment, bacteria, and algae, maintaining your family's health and complying with UAE municipality standards." },
  "solar-panel-installation": { title: "Expert Solar Panel Installation in the UAE", description: "Reduce your energy bills and embrace sustainability with professional solar panel installation and maintenance in the UAE. Our verified, certified technicians in Dubai, Abu Dhabi, and Sharjah design and install high-efficiency solar systems tailored to your property's energy needs, ensuring maximum ROI and reliable performance." },
  "tile-marble-workers": { title: "Skilled Tile & Marble Workers in the UAE", description: "Enhance your property with expert tile and marble installation services across Dubai, Abu Dhabi, and Sharjah. Our verified craftsmen specialize in flooring, wall cladding, and intricate mosaic work, delivering precise, durable, and visually stunning results for both residential and commercial spaces." },
  "aluminum-glass-works": { title: "Professional Aluminum & Glass Works in the UAE", description: "Upgrade your property with high-quality aluminum and glass fabrication services in the UAE. Our verified specialists in Dubai, Abu Dhabi, and Sharjah provide custom windows, doors, partitions, and storefront installations, combining durability, thermal efficiency, and modern aesthetics." },
  "gypsum-false-ceiling": { title: "Expert Gypsum & False Ceiling Services in the UAE", description: "Elevate your interior design with professional gypsum board and false ceiling installation across the UAE. Our verified contractors in Dubai, Abu Dhabi, and Sharjah create sleek, modern ceiling designs with integrated lighting, offering excellent acoustic and thermal insulation for homes and offices." },
  "smart-home-installation": { title: "Smart Home Automation Installation in the UAE", description: "Upgrade your living experience with professional smart home installation services in Dubai, Abu Dhabi, and Sharjah. Our verified technicians seamlessly integrate lighting, climate control, security, and entertainment systems, providing intuitive, centralized automation for ultimate comfort, convenience, and energy efficiency." },
  "car-detailing": { title: "Premium Car Detailing Services in the UAE", description: "Restore your vehicle's showroom shine with premium car detailing services across the UAE. Our verified professionals in Dubai, Abu Dhabi, and Sharjah offer comprehensive interior deep-cleaning, exterior paint correction, ceramic coating, and polishing, protecting your investment with meticulous care." },
  "tire-shop": { title: "Reliable Tire Shops & Services in the UAE", description: "Ensure your safety on the road with trusted tire shops and automotive services in Dubai, Abu Dhabi, and Sharjah. EasyFinder connects you with verified providers offering tire sales, puncture repair, wheel balancing, and alignment, ensuring optimal performance and longevity for your vehicle." },
  "car-electrical": { title: "Expert Car Electrical Repair in the UAE", description: "Resolve automotive electrical issues quickly with certified car electricians in Dubai, Abu Dhabi, and Sharjah. Our verified professionals specialize in battery replacement, alternator repair, wiring diagnostics, and lighting fixes, ensuring your vehicle's electrical systems function safely and reliably." },
  "car-ac-repair": { title: "Professional Car AC Repair in the UAE", description: "Stay cool on the road with expert car air conditioning repair and gas refill services across the UAE. Our verified automotive technicians in Dubai, Abu Dhabi, and Sharjah quickly diagnose and fix AC leaks, compressor issues, and cooling failures, restoring your vehicle's comfort efficiently." },
  "car-tinting": { title: "Premium Car Window Tinting in the UAE", description: "Protect your vehicle's interior and enhance privacy with professional car window tinting services in Dubai, Abu Dhabi, and Sharjah. Our verified installers use high-quality, RTA-compliant films that block harmful UV rays, reduce heat, and provide a sleek, sophisticated finish to your car." },
  "videographers": { title: "Professional Videographers in the UAE", description: "Bring your story to life with talented, professional videographers in Dubai, Abu Dhabi, and Sharjah. Whether you need corporate promotional videos, event coverage, or cinematic wedding films, EasyFinder connects you with verified creators who deliver high-definition, engaging visual content." },
  "event-planners": { title: "Expert Event Planning Services in the UAE", description: "Execute flawless events with experienced, verified event planners in Dubai, Abu Dhabi, and the wider UAE. From corporate conferences and product launches to private parties and galas, our professionals handle logistics, vendor coordination, and creative design, ensuring a memorable and seamless experience." },
  "catering-services": { title: "Premium Catering Services in the UAE", description: "Delight your guests with exceptional catering services across Dubai, Abu Dhabi, and Sharjah. EasyFinder connects you with verified, hygienic, and creative catering companies offering diverse menus for weddings, corporate events, and private gatherings, ensuring delicious, high-quality food and impeccable service." },
  "makeup-artists": { title: "Professional Makeup Artists in the UAE", description: "Look and feel your absolute best with talented, professional makeup artists in Dubai, Abu Dhabi, and Sharjah. Whether for your wedding day, a special event, or a photoshoot, our verified artists use premium products to create flawless, long-lasting, and personalized looks tailored to your style." },
  "bakeries": { title: "Custom Bakeries & Confectionery in the UAE", description: "Celebrate life's sweet moments with artisan bakeries and custom cake designers across the UAE. Our verified bakers in Dubai, Abu Dhabi, and Sharjah create stunning, delicious cakes, pastries, and desserts for weddings, birthdays, and corporate events, using high-quality, fresh ingredients." },
  "document-clearing-pro": { title: "Trusted PRO & Document Clearing Services in the UAE", description: "Navigate UAE bureaucracy effortlessly with reliable, verified PRO and document clearing services in Dubai, Abu Dhabi, and Sharjah. Our experts handle visa processing, trade license renewals, document attestation, and government approvals quickly and accurately, saving you valuable time and hassle." },
  "translation-services": { title: "Professional Translation Services in the UAE", description: "Bridge language barriers with certified, professional translation and interpretation services across the UAE. Our verified linguists in Dubai, Abu Dhabi, and Sharjah provide accurate, culturally appropriate translations for legal, medical, corporate, and technical documents, ensuring clear and compliant communication." },
  "personal-trainers": { title: "Certified Personal Trainers in the UAE", description: "Achieve your fitness goals with experienced, certified personal trainers in Dubai, Abu Dhabi, and Sharjah. EasyFinder connects you with verified fitness professionals who provide customized workout plans, nutritional guidance, and motivational support, helping you build strength, endurance, and a healthier lifestyle." },
  "tutors-private-teachers": { title: "Expert Tutors & Private Teachers in the UAE", description: "Support your child's academic success with qualified, verified tutors and private teachers across the UAE. Whether you need help with school curriculum, exam preparation, or language learning in Dubai, Abu Dhabi, or Sharjah, our educators provide personalized, effective, and engaging one-on-one lessons." },
  "salons-beauty": { title: "Top-Rated Beauty Salons in the UAE", description: "Pamper yourself at the best beauty salons in Dubai, Abu Dhabi, and Sharjah. EasyFinder connects you with verified, hygienic, and professional salons offering a full range of services, including hair styling, nail care, facials, and waxing, ensuring you leave feeling refreshed and beautiful." },
  "barbers": { title: "Premium Barbershops in the UAE", description: "Maintain your sharp look with top-rated, professional barbers in Dubai, Abu Dhabi, and Sharjah. Our verified barbershops offer precision haircuts, beard trimming, hot towel shaves, and grooming treatments in a relaxed, masculine environment, using high-quality products for the perfect finish." },
  "massage-therapists": { title: "Licensed Massage Therapists in the UAE", description: "Relax and rejuvenate with professional, licensed massage therapy services across the UAE. Our verified therapists in Dubai, Abu Dhabi, and Sharjah offer a variety of treatments, including Swedish, deep tissue, and sports massage, helping to relieve stress, reduce muscle tension, and promote overall well-being." },
  "driving-instructors": { title: "Certified Driving Instructors in the UAE", description: "Gain confidence behind the wheel with patient, certified driving instructors in Dubai, Abu Dhabi, and Sharjah. EasyFinder connects you with verified professionals who offer comprehensive, RTA-aligned driving lessons, helping you master the rules of the road and pass your driving test with ease." },
  "web-designers": { title: "Creative Web Designers & Developers in the UAE", description: "Establish a powerful online presence with talented, verified web designers and developers in Dubai, Abu Dhabi, and Sharjah. Our professionals create responsive, user-friendly, and visually stunning websites tailored to your brand, ensuring optimal performance, SEO, and a seamless user experience." },
  "it-support": { title: "Reliable IT Support Services in the UAE", description: "Keep your business running smoothly with professional IT support and computer repair services across the UAE. Our verified technicians in Dubai, Abu Dhabi, and Sharjah provide rapid troubleshooting, network setup, hardware repair, and cybersecurity solutions for homes and small-to-medium businesses." },
  "digital-marketing": { title: "Expert Digital Marketing Agencies in the UAE", description: "Grow your brand's online presence with verified digital marketing experts in Dubai, Abu Dhabi, and Sharjah. Our professionals specialize in SEO, social media management, PPC advertising, and content creation, delivering data-driven strategies that increase visibility, engagement, and conversions." },
  "masons-bricklayers": { title: "Skilled Masons & Bricklayers in the UAE", description: "Build with confidence using experienced, verified masons and bricklayers in Dubai, Abu Dhabi, and Sharjah. Our craftsmen specialize in structural brickwork, block laying, and stone masonry, delivering durable, precise, and high-quality construction work for residential and commercial projects." },
  "welding-services": { title: "Professional Welding & Fabrication in the UAE", description: "Ensure structural integrity with certified welding and metal fabrication services across the UAE. Our verified professionals in Dubai, Abu Dhabi, and Sharjah handle MIG, TIG, and arc welding for gates, railings, structural repairs, and custom metalwork, guaranteeing strong, safe, and precise results." },
  "generator-repair": { title: "Expert Generator Repair & Maintenance in the UAE", description: "Never lose power with reliable generator installation, repair, and maintenance services in Dubai, Abu Dhabi, and Sharjah. Our verified technicians provide rapid diagnostics, part replacements, and routine servicing for residential and commercial backup generators, ensuring uninterrupted power supply." },
  "elevator-maintenance": { title: "Certified Elevator Maintenance in the UAE", description: "Ensure the safety and reliability of your building's vertical transport with certified elevator maintenance and repair services in the UAE. Our verified technicians in Dubai, Abu Dhabi, and Sharjah provide routine inspections, emergency repairs, and modernization for all elevator and lift systems." },
  "signage-branding": { title: "Custom Signage & Branding Services in the UAE", description: "Make a lasting impression with high-quality, custom signage and branding solutions across the UAE. Our verified experts in Dubai, Abu Dhabi, and Sharjah design and install illuminated signs, vehicle wraps, banners, and 3D lettering, elevating your brand's visibility and professional image." },
  "packers-movers": { title: "Comprehensive Packers & Movers in the UAE", description: "Experience a seamless relocation with top-rated packers and movers in Dubai, Abu Dhabi, and Sharjah. Our verified companies offer end-to-end services, including professional packing, secure transportation, customs clearance, and storage solutions, ensuring your belongings arrive safely and on time." },
  "junk-removal": { title: "Fast & Reliable Junk Removal in the UAE", description: "Reclaim your space with professional, eco-friendly junk removal and disposal services across the UAE. Our verified teams in Dubai, Abu Dhabi, and Sharjah handle the heavy lifting, safely removing construction debris, old furniture, and household waste, ensuring proper recycling and disposal." }
};

export function getCategorySEO(slug: string | undefined) {
  if (!slug) return null;
  return categorySEOData[slug.toLowerCase()] || null;
}